### ISSUE TITLE
Explorer losing old information

### ISSUE THREAD

**Issue by WorldChainS** [web3labs/epirus-free#35] opened 2020-11-20 01:08 UTC
I am facing an issue of losing old information on Epirus explorer, after it has been running for a while.
For example, I set it up, it starts up with full information and after a day or two it loses old blocks, tokens, transactions, ... In MongoDB the data seems to be deleted.

When I do a new action on the blockchain, that one is visible until some time passes again.

**Comment by SweeXordious** [comment] 2020-11-25 12:53
@WorldChainS I have been trying to replicate your issue but in vain.
I spin up a quorum node using `npx` then started flooding it with transactions (~100 transaction per block) etc.
And I have been using the explorer against it and it seems to work fine. I am over 10k blocks and everything seems to be working fine.
Maybe check docker allowed storage parameters as it might have been saturated.

**Comment by WorldChainS** [comment] 2020-11-26 15:45
I use the private network geth, the total block height is about 3 million, and the historical database is lost once a day on average

**Comment by SweeXordious** [comment] 2020-11-26 15:58
I am not able to reproduce. Would you please provide the steps to reproduce ?  I have been running an instance for few days now and everything seems alright, no losses.
Also, does the Db get truncated at the beginning ? Or you're loosing data from different places of the timeline ?

**Comment by SweeXordious** [comment] 2021-12-08 19:39
Closing. Please reopen if needed.

**Closed by SweeXordious** 2021-12-08 19:39 UTC
