### ISSUE TITLE
Not starting without license key

### ISSUE THREAD

**Issue by shspsleo** [web3labs/epirus-free#32] opened 2020-11-10 06:32 UTC
I'm trying to connect to a my private chain on the docker image.

And I try to start up the explorer then it shows the failed.

Does anyone know how to solve it?

**Comment by shspsleo** [comment] 2020-11-10 11:02
it looks like error on 'New Relic for Node.js'

**Comment by SweeXordious** [comment] 2020-11-11 01:28
@shspsleo Check which interfaces your private chain is listening on. 

If that didn't help, please provide more details on the execution ?
What is the command you used to run the explorer ?
A copy of the logs ?
Are you running against `ganache` or `geth` ... ? If so, please provide the command you used to run it ?

**Comment by yjfcn** [comment] 2020-11-18 08:25
I have the same error while connect to my private chain. I am running quorum against geth.
The command I run epirus is:
docker-compose pull
NODE_ENDPOINT=http://<node_endpoint> docker-compose up

The following is the log for image web3labs/epirus-free-web:latest
> epirus-ui@1.0.0 build /app
> npm-run-all --parallel build:client build:server


> epirus-ui@1.0.0 build:client /app
> next build


> epirus-ui@1.0.0 build:server /app
> tsc -p ./tsconfig.server.json

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Creating an optimized production build...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
> Using external babel configuration
> Location: "/app/.babelrc"

> epirus-ui@1.0.0 build /app
> npm-run-all --parallel build:client build:server


> epirus-ui@1.0.0 build:client /app
> next build


> epirus-ui@1.0.0 build:server /app
> tsc -p ./tsconfig.server.json

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
> Using external babel configuration
> Location: "/app/.babelrc"

Compiled successfully.

Automatically optimizing pages...

Page                                                           Size     First Load
┌ ○ /                                                          686 B        340 kB
├   /_app                                                      3.53 kB     84.6 kB
├ λ /_error                                                    2.62 kB      336 kB
├ ○ /accounts                                                  733 B        340 kB
├ ○ /accounts/[detailsHash]                                    235 B        412 kB
├ ○ /accounts/[detailsHash]/[tab]                              194 B        412 kB
├ ○ /authenticating                                            1.05 kB      340 kB
├ ○ /blocks                                                    2.42 kB      403 kB
├ ○ /blocks/[detailsHash]                                      234 B        412 kB
├ ○ /blocks/[detailsHash]/[tab]                                193 B        412 kB
├ ○ /contracts                                                 2.39 kB      403 kB
├ ○ /contracts/[detailsHash]                                   236 B        412 kB
├ ○ /contracts/[detailsHash]/[tab]                             195 B        412 kB
├ ○ /creating-environment                                      1.11 kB      119 kB
├ ○ /dashboard                                                 6.39 kB      454 kB
├ ○ /events                                                    2.43 kB      403 kB
├ ○ /lab                                                       819 B        328 kB
├ ○ /lab/chart-overflow                                        5.15 kB      379 kB
├ ○ /lab/fonts-and-weights                                     2.19 kB     95.5 kB
├ ○ /lab/interaction-animations                                1.17 kB      148 kB
├ ○ /log-in                                                    2.71 kB      186 kB
├ ○ /metadata                                                  4.99 kB      406 kB
├ ○ /metadata/[detailsHash]                                    2.85 kB      411 kB
├ ○ /metadata/[detailsHash]/[tab]                              2.83 kB      411 kB
├ ○ /network                                                   2.08 kB      411 kB
├ ○ /network/[tab]                                             2.06 kB      411 kB
├ ○ /profile                                                   1.56 kB      341 kB
├ ○ /search                                                    705 B        340 kB
├ ○ /silent-redirect                                           532 B        151 kB
├ ○ /tokens                                                    2.41 kB      403 kB
├ ○ /tokens/[detailsHash]                                      234 B        412 kB
├ ○ /tokens/[detailsHash]/[tab]                                191 B        412 kB
├ ○ /transactions                                              2.41 kB      403 kB
├ ○ /transactions/[detailsHash]                                236 B        413 kB
└ ○ /transactions/[detailsHash]/[tab]                          195 B        413 kB
+ shared by all                                                84.6 kB
  ├ static/_buildManifest.js                                   1.04 kB
  ├ static/pages/_app.js                                       3.53 kB
  ├ chunks/3cda8313a3a3f677236b599adf0bbdc50315cda7.eb4450.js  2.35 kB
  ├ chunks/58a4fa50c870dd241d27a70759d46c09bf2fc784.af6da0.js  8.93 kB
  ├ chunks/6cd246d68f2f4a2bb30dd9346840047e8d7cfecd.70a12b.js  13.9 kB
  ├ chunks/bae46246ca02549fc014e271b62ec042f2a8580d.81c4dc.js  8.28 kB
  ├ chunks/framework.c5d16c.js                                 40.7 kB
  ├ runtime/main.f041cb.js                                     5.05 kB
  └ runtime/webpack.b65cab.js                                  746 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)


> epirus-ui@1.0.0 start /app
> NODE_ENV=production node dist

New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
    at onNextTick (/app/node_modules/newrelic/lib/agent.js:227:16)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
{"level":30,"time":1605685429772,"pid":109,"hostname":"17bb4aed8a8e","msg":"Server listening at http://0.0.0.0:3000","v":1}
> Ready on http://localhost:3000

**Comment by SweeXordious** [comment] 2020-11-25 12:50
@yjfcn Sorry for the late reply. I have been trying to reproduce, but in vain. Everything seemed to work fine for me.
I think you should run using:
```
NODE_ENDPOINT=<endpoint> docker-compose -f docker-compose.yml -f epirus-extensions/docker-compose-quorum.yml up
```
when running against quorum. It is specified in the [documentation](https://github.com/web3labs/epirus-free/blob/master/examples/Quorum_Example.md)

**Comment by nicexe** [comment] 2021-01-04 13:42
substitute `<endpoint>` with your actual endpoint

**Comment by SweeXordious** [comment] 2021-12-08 19:47
Closing. Please reopen if needed.

**Closed by SweeXordious** 2021-12-08 19:47 UTC
