### ISSUE TITLE
error ingestion

### ISSUE THREAD

**Issue by dvgoyeneche** [web3labs/epirus-free#33] opened 2020-11-15 15:18 UTC
ingestion_1_a56d5eddbad8 | 2020-11-15 15:14:28.876  INFO 1 --- [   scheduling-1] i.e.e.i.e.s.BlockHeightExtractionService : Found: 8655
ingestion_1_a56d5eddbad8 | 2020-11-15 15:14:28.887 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
ingestion_1_a56d5eddbad8 |
ingestion_1_a56d5eddbad8 | kotlin.KotlinNullPointerException: null
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.loader.BlockCommandExtractor.getQuorumInput(BlockCommandExtractor.kt:177) ~[loader-2.0.jar!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.loader.BlockCommandExtractor.privateTransactionPayload(BlockCommandExtractor.kt:142) ~[loader-2.0.jar!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.loader.BlockCommandExtractor.getTransaction(BlockCommandExtractor.kt:122) ~[loader-2.0.jar!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.loader.BlockCommandExtractor.extract(BlockCommandExtractor.kt:66) ~[loader-2.0.jar!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.app.SynchronizedBlockCommandNotifier.added(SynchronizedBlockCommandNotifier.kt:13) ~[classes!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.extractor.service.BlockHeightExtractionService.ingest(BlockHeightExtractionService.kt:51) ~[extractor-2.0.jar!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.extractor.service.BlockHeightExtractionService.ingestBlockNumberIfReady(BlockHeightExtractionService.kt:31) ~[extractor-2.0.jar!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.extractor.service.BlockHeightExtractionService.ingestNextBlock(BlockHeightExtractionService.kt:19) ~[extractor-2.0.jar!/:na]
ingestion_1_a56d5eddbad8 |      at io.epirus.explorer.ingestion.app.IngestionService.checkBlockHeight(IngestionService.kt:67) ~[classes!/:na]
ingestion_1_a56d5eddbad8 |      at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1_a56d5eddbad8 |      at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
ingestion_1_a56d5eddbad8 |      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
ingestion_1_a56d5eddbad8 |      at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

**Comment by SweeXordious** [comment] 2020-11-15 18:12
Hello,
Please provide more details ?
What were you trying to do ?
Which commands did you run ?
Which network you're running this against ? How did you spin it up ?
More logs if possible

**Comment by dvgoyeneche** [comment] 2020-11-15 18:34
I want to use epirus-free as a blockchain explorer for my quorum network (quorum version 2.5.0)
I execute this command: 
NODE_ENDPOINT=http://192.168.2.104:22000 docker-compose up
It reads 8655 blocks and after that is always throwing this error

**Comment by SweeXordious** [comment] 2020-11-16 13:35
Will try to reproduce and come back to you

**Comment by SweeXordious** [comment] 2020-11-25 12:57
@dvgoyeneche  Sorry for the late reply. I have been trying to reproduce, but in vain. Everything seemed to work fine for me. I have ingested more than 10k blocks for tests and couldn't reproduce.

Btw, I think you should run using:
```
NODE_ENDPOINT=<endpoint> docker-compose -f docker-compose.yml -f epirus-extensions/docker-compose-quorum.yml up
```
when running against quorum. It is specified in the [documentation](https://github.com/web3labs/epirus-free/blob/master/examples/Quorum_Example.md)

**Comment by teslasw** [comment] 2020-12-02 03:37
@dvgoyeneche I have this exact issue, fails on 266 even though I have 270 did you find solution?

**Comment by SweeXordious** [comment] 2020-12-02 12:09
@teslasw If you are running this in a box we can access to and see what is happening. Please email us at : support@web3labs.com

**Comment by dvgoyeneche** [comment] 2020-12-02 12:29
Simply log into the mongodb container and update the id of the last block to the id of the block failing...
I consider there is a bug in epirus

**Comment by dvgoyeneche** [comment] 2020-12-02 12:29
> @dvgoyeneche I have this exact issue, fails on block height 266 even though I have 270. Did you happen to find a solution?

Simply log into the mongodb container and update the id of the last block to the id of the block failing...
I consider there is a bug in epirus

**Comment by xiaopidanO** [comment] 2021-01-05 16:19
> > @dvgoyeneche I have this exact issue, fails on block height 266 even though I have 270. Did you happen to find a solution?
> 
> Simply log into the mongodb container and update the id of the last block to the id of the block failing...
> I consider there is a bug in epirus
I also encountered similar problems. Could you please tell me how to do your specific operation? How to enter into the MongoDB container and update update the id of the last block to the id of the block failing... At the same time, there was also a problem with my network module. I built a three-node network, but the network module always showed -1,and when I click in the network module, it return 500

**Comment by SweeXordious** [comment] 2021-12-08 19:42
Closing. Please reopen if issue still persists.

**Closed by SweeXordious** 2021-12-08 19:42 UTC
